// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb codegen.

#pragma once

#include <cstdint>
#include <string>
#include <vector>
#include <optional>
#include <memory>
#include "spacetimedb/bsatn/bsatn.h"

namespace SpacetimeDb::Internal {

class AlgebraicType {
public:
    enum class Tag {
        Ref = 0,
        Sum = 1,
        Product = 2,
        Array = 3,
        String = 4,
        Bool = 5,
        I8 = 6,
        U8 = 7,
        I16 = 8,
        U16 = 9,
        I32 = 10,
        U32 = 11,
        I64 = 12,
        U64 = 13,
        I128 = 14,
        U128 = 15,
        I256 = 16,
        U256 = 17,
        F32 = 18,
        F64 = 19,
    };

private:
    Tag tag_;
    // TODO: Implement variant storage

public:
    Tag get_tag() const { return tag_; }

    // BSATN serialization support
    void bsatn_serialize(SpacetimeDb::bsatn::Writer& writer) const;
    void bsatn_deserialize(SpacetimeDb::bsatn::Reader& reader);
};
} // namespace SpacetimeDb::Internal
// Type registration macro
#define SPACETIMEDB_REGISTER_TYPE_AlgebraicType \
    namespace spacetimedb { \
    namespace detail { \
    template<> \
    struct TypeRegistrar<SpacetimeDb::Internal::AlgebraicType> { \
        static AlgebraicTypeRef register_type(TypeContext& ctx) { \
            return ctx.add(AlgebraicType::Sum(std::make_unique<SumType>(std::vector<SumType::Variant>{
    {"Ref", AlgebraicType::U32()},
    {"Sum", AlgebraicType::Ref(4)},
    {"Product", AlgebraicType::Ref(6)},
    {"Array", AlgebraicType::Ref(3)},
    {"String", /* unhandled algebraic type */},
    {"Bool", /* unhandled algebraic type */},
    {"I8", /* unhandled algebraic type */},
    {"U8", /* unhandled algebraic type */},
    {"I16", /* unhandled algebraic type */},
    {"U16", /* unhandled algebraic type */},
    {"I32", /* unhandled algebraic type */},
    {"U32", /* unhandled algebraic type */},
    {"I64", /* unhandled algebraic type */},
    {"U64", /* unhandled algebraic type */},
    {"I128", /* unhandled algebraic type */},
    {"U128", /* unhandled algebraic type */},
    {"I256", /* unhandled algebraic type */},
    {"U256", /* unhandled algebraic type */},
    {"F32", /* unhandled algebraic type */},
    {"F64", /* unhandled algebraic type */}
}))); \
        } \
    }; \
    } /* namespace detail */ \
    } /* namespace spacetimedb */

