// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb codegen.

#pragma once

#include <cstdint>
#include <string>
#include <vector>
#include <optional>
#include <memory>
#include "spacetimedb/bsatn/bsatn.h"

namespace SpacetimeDb::Internal {

enum class IndexType : uint8_t {
    BTree = 0,
    Hash = 1,
};
} // namespace SpacetimeDb::Internal
#include "spacetimedb/macros.h"
SPACETIMEDB_TYPE(IndexType)
SPACETIMEDB_DATA_CONTRACT
SPACETIMEDB_REGISTER_TYPE(IndexType)
