// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb codegen.

#pragma once

#include <cstdint>
#include <string>
#include <vector>
#include <optional>
#include <memory>
#include "spacetimedb/bsatn/bsatn.h"

namespace SpacetimeDb::Internal {

enum class IndexType {
    BTree = 0,
    Hash = 1,
};
} // namespace SpacetimeDb::Internal

// BSATN serialization for IndexType
namespace SpacetimeDb::bsatn {
    inline void serialize(Writer& w, const SpacetimeDb::Internal::IndexType& value) {
        w.write_u8(static_cast<uint8_t>(value));
    }

    template<>
    inline SpacetimeDb::Internal::IndexType deserialize<SpacetimeDb::Internal::IndexType>(Reader& r) {
        return static_cast<SpacetimeDb::Internal::IndexType>(r.read_u8());
    }
}
