// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb codegen.

#pragma once

#include <cstdint>
#include <string>
#include <vector>
#include <optional>
#include <memory>
#include "spacetimedb/bsatn/bsatn.h"

namespace SpacetimeDb::Internal {

enum class Lifecycle {
    Init = 0,
    OnConnect = 1,
    OnDisconnect = 2,
};
} // namespace SpacetimeDb::Internal

// BSATN serialization for Lifecycle
namespace SpacetimeDb::bsatn {
    inline void serialize(Writer& w, const SpacetimeDb::Internal::Lifecycle& value) {
        w.write_u8(static_cast<uint8_t>(value));
    }

    template<>
    inline SpacetimeDb::Internal::Lifecycle deserialize<SpacetimeDb::Internal::Lifecycle>(Reader& r) {
        return static_cast<SpacetimeDb::Internal::Lifecycle>(r.read_u8());
    }
}
