// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb codegen.

#pragma once

#include <cstdint>
#include <string>
#include <vector>
#include <optional>
#include <memory>
#include "spacetimedb/bsatn/bsatn.h"
#include "AlgebraicType.g.h"

namespace SpacetimeDb::Internal {

struct ProductTypeElement {
    std::optional<std::string> name;
    SpacetimeDb::Internal::AlgebraicType algebraic_type;

    ProductTypeElement() = default;

    ProductTypeElement(std::optional<std::string> name, SpacetimeDb::Internal::AlgebraicType algebraic_type)
        : name(name), algebraic_type(algebraic_type) {}

    // BSATN serialization support
    void bsatn_serialize(SpacetimeDb::bsatn::Writer& writer) const;
    void bsatn_deserialize(SpacetimeDb::bsatn::Reader& reader);

    // Static factory method for BSATN deserialization
    static ProductTypeElement from_bsatn(SpacetimeDb::bsatn::Reader& reader) {
        ProductTypeElement result;
        result.bsatn_deserialize(reader);
        return result;
    }
};
} // namespace SpacetimeDb::Internal
// Type registration macro
#define SPACETIMEDB_REGISTER_TYPE_ProductTypeElement \
    namespace spacetimedb { \
    namespace detail { \
    template<> \
    struct TypeRegistrar<SpacetimeDb::Internal::ProductTypeElement> { \
        static AlgebraicTypeRef register_type(TypeContext& ctx) { \
            return ctx.add(AlgebraicType::Product(std::make_unique<ProductType>(std::vector<ProductType::Element>{
    {"name", AlgebraicType::Option(AlgebraicType::String())},
    {"algebraic_type", AlgebraicType::Ref(3)}
}))); \
        } \
    }; \
    } /* namespace detail */ \
    } /* namespace spacetimedb */

