// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb codegen.

#pragma once

#include <cstdint>
#include <string>
#include <vector>
#include <optional>
#include <memory>
#include "spacetimedb/bsatn/bsatn.h"
#include "ProductTypeElement.g.h"

namespace SpacetimeDb::Internal {

struct ProductType {
    std::vector<SpacetimeDb::Internal::ProductTypeElement> elements;

    ProductType() = default;

    ProductType(std::vector<SpacetimeDb::Internal::ProductTypeElement> elements)
        : elements(elements) {}

    // BSATN serialization support
    void bsatn_serialize(SpacetimeDb::bsatn::Writer& writer) const;
    void bsatn_deserialize(SpacetimeDb::bsatn::Reader& reader);

    // Static factory method for BSATN deserialization
    static ProductType from_bsatn(SpacetimeDb::bsatn::Reader& reader) {
        ProductType result;
        result.bsatn_deserialize(reader);
        return result;
    }
};
} // namespace SpacetimeDb::Internal
#include "spacetimedb/macros.h"
SPACETIMEDB_REGISTER_TYPE(ProductType)
