// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb codegen.

#pragma once

#include <cstdint>
#include <string>
#include <vector>
#include <optional>
#include <memory>
#include "spacetimedb/bsatn/bsatn.h"

namespace SpacetimeDb::Internal {

struct RawConstraintDefV8 {
    std::string constraint_name;
    uint8_t constraints;
    std::vector<uint16_t> columns;

    RawConstraintDefV8() = default;

    RawConstraintDefV8(std::string constraint_name, uint8_t constraints, std::vector<uint16_t> columns)
        : constraint_name(constraint_name), constraints(constraints), columns(columns) {}

    // BSATN serialization support
    void bsatn_serialize(SpacetimeDb::bsatn::Writer& writer) const;
    void bsatn_deserialize(SpacetimeDb::bsatn::Reader& reader);

    // Static factory method for BSATN deserialization
    static RawConstraintDefV8 from_bsatn(SpacetimeDb::bsatn::Reader& reader) {
        RawConstraintDefV8 result;
        result.bsatn_deserialize(reader);
        return result;
    }
};
} // namespace SpacetimeDb::Internal
