// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb codegen.

#pragma once

#include <cstdint>
#include <string>
#include <vector>
#include <optional>
#include <memory>
#include "spacetimedb/bsatn/bsatn.h"
#include "AlgebraicType.g.h"

namespace SpacetimeDb::Internal {

struct RawColumnDefV8 {
    std::string col_name;
    SpacetimeDb::Internal::AlgebraicType col_type;

    RawColumnDefV8() = default;

    RawColumnDefV8(std::string col_name, SpacetimeDb::Internal::AlgebraicType col_type)
        : col_name(col_name), col_type(col_type) {}

    // BSATN serialization support
    void bsatn_serialize(SpacetimeDb::bsatn::Writer& writer) const;
    void bsatn_deserialize(SpacetimeDb::bsatn::Reader& reader);

    // Static factory method for BSATN deserialization
    static RawColumnDefV8 from_bsatn(SpacetimeDb::bsatn::Reader& reader) {
        RawColumnDefV8 result;
        result.bsatn_deserialize(reader);
        return result;
    }
};
} // namespace SpacetimeDb::Internal
// Type registration macro
#define SPACETIMEDB_REGISTER_TYPE_RawColumnDefV8 \
    namespace spacetimedb { \
    namespace detail { \
    template<> \
    struct TypeRegistrar<SpacetimeDb::Internal::RawColumnDefV8> { \
        static AlgebraicTypeRef register_type(TypeContext& ctx) { \
            return ctx.add(AlgebraicType::Product(std::make_unique<ProductType>(std::vector<ProductType::Element>{
    {"col_name", AlgebraicType::String()},
    {"col_type", AlgebraicType::Ref(3)}
}))); \
        } \
    }; \
    } /* namespace detail */ \
    } /* namespace spacetimedb */

