// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb codegen.

#pragma once

#include <cstdint>
#include <string>
#include <vector>
#include <optional>
#include <memory>
#include "spacetimedb/bsatn/bsatn.h"
#include "RawConstraintDataV9.g.h"

namespace SpacetimeDb::Internal {

struct RawConstraintDefV9 {
    std::optional<std::string> name;
    SpacetimeDb::Internal::RawConstraintDataV9 data;

    RawConstraintDefV9() = default;

    RawConstraintDefV9(std::optional<std::string> name, SpacetimeDb::Internal::RawConstraintDataV9 data)
        : name(name), data(data) {}

    // BSATN serialization support
    void bsatn_serialize(SpacetimeDb::bsatn::Writer& writer) const;
    void bsatn_deserialize(SpacetimeDb::bsatn::Reader& reader);

    // Static factory method for BSATN deserialization
    static RawConstraintDefV9 from_bsatn(SpacetimeDb::bsatn::Reader& reader) {
        RawConstraintDefV9 result;
        result.bsatn_deserialize(reader);
        return result;
    }
};
} // namespace SpacetimeDb::Internal
// Type registration macro
#define SPACETIMEDB_REGISTER_TYPE_RawConstraintDefV9 \
    namespace spacetimedb { \
    namespace detail { \
    template<> \
    struct TypeRegistrar<SpacetimeDb::Internal::RawConstraintDefV9> { \
        static AlgebraicTypeRef register_type(TypeContext& ctx) { \
            return ctx.add(AlgebraicType::Product(std::make_unique<ProductType>(std::vector<ProductType::Element>{
    {"name", AlgebraicType::Option(AlgebraicType::String())},
    {"data", AlgebraicType::Ref(23)}
}))); \
        } \
    }; \
    } /* namespace detail */ \
    } /* namespace spacetimedb */

