// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb codegen.

#pragma once

#include <cstdint>
#include <string>
#include <vector>
#include <optional>
#include <memory>
#include "spacetimedb/bsatn/bsatn.h"
#include "RawIndexAlgorithm.g.h"

namespace SpacetimeDb::Internal {

struct RawIndexDefV9 {
    std::optional<std::string> name;
    std::optional<std::string> accessor_name;
    SpacetimeDb::Internal::RawIndexAlgorithm algorithm;

    RawIndexDefV9() = default;

    RawIndexDefV9(std::optional<std::string> name, std::optional<std::string> accessor_name, SpacetimeDb::Internal::RawIndexAlgorithm algorithm)
        : name(name), accessor_name(accessor_name), algorithm(algorithm) {}

    // BSATN serialization support
    void bsatn_serialize(SpacetimeDb::bsatn::Writer& writer) const;
    void bsatn_deserialize(SpacetimeDb::bsatn::Reader& reader);

    // Static factory method for BSATN deserialization
    static RawIndexDefV9 from_bsatn(SpacetimeDb::bsatn::Reader& reader) {
        RawIndexDefV9 result;
        result.bsatn_deserialize(reader);
        return result;
    }
};
} // namespace SpacetimeDb::Internal
// Type registration macro
#define SPACETIMEDB_REGISTER_TYPE_RawIndexDefV9 \
    namespace spacetimedb { \
    namespace detail { \
    template<> \
    struct TypeRegistrar<SpacetimeDb::Internal::RawIndexDefV9> { \
        static AlgebraicTypeRef register_type(TypeContext& ctx) { \
            return ctx.add(AlgebraicType::Product(std::make_unique<ProductType>(std::vector<ProductType::Element>{
    {"name", AlgebraicType::Option(AlgebraicType::String())},
    {"accessor_name", AlgebraicType::Option(AlgebraicType::String())},
    {"algorithm", AlgebraicType::Ref(21)}
}))); \
        } \
    }; \
    } /* namespace detail */ \
    } /* namespace spacetimedb */

