// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb codegen.

#pragma once

#include <cstdint>
#include <string>
#include <vector>
#include <optional>
#include <memory>
#include "spacetimedb/bsatn/bsatn.h"
#include "RawTableDefV9.g.h"
#include "RawReducerDefV9.g.h"
#include "Typespace.g.h"
#include "RawRowLevelSecurityDefV9.g.h"
#include "RawMiscModuleExportV9.g.h"
#include "RawTypeDefV9.g.h"

namespace SpacetimeDb::Internal {

struct RawModuleDefV9 {
    SpacetimeDb::Internal::Typespace typespace;
    std::vector<SpacetimeDb::Internal::RawTableDefV9> tables;
    std::vector<SpacetimeDb::Internal::RawReducerDefV9> reducers;
    std::vector<SpacetimeDb::Internal::RawTypeDefV9> types;
    std::vector<SpacetimeDb::Internal::RawMiscModuleExportV9> misc_exports;
    std::vector<SpacetimeDb::Internal::RawRowLevelSecurityDefV9> row_level_security;

    RawModuleDefV9() = default;

    RawModuleDefV9(SpacetimeDb::Internal::Typespace typespace, std::vector<SpacetimeDb::Internal::RawTableDefV9> tables, std::vector<SpacetimeDb::Internal::RawReducerDefV9> reducers, std::vector<SpacetimeDb::Internal::RawTypeDefV9> types, std::vector<SpacetimeDb::Internal::RawMiscModuleExportV9> misc_exports, std::vector<SpacetimeDb::Internal::RawRowLevelSecurityDefV9> row_level_security)
        : typespace(typespace), tables(tables), reducers(reducers), types(types), misc_exports(misc_exports), row_level_security(row_level_security) {}

    // BSATN serialization support
    void bsatn_serialize(SpacetimeDb::bsatn::Writer& writer) const;
    void bsatn_deserialize(SpacetimeDb::bsatn::Reader& reader);

    // Static factory method for BSATN deserialization
    static RawModuleDefV9 from_bsatn(SpacetimeDb::bsatn::Reader& reader) {
        RawModuleDefV9 result;
        result.bsatn_deserialize(reader);
        return result;
    }
};
} // namespace SpacetimeDb::Internal
#include "spacetimedb/macros.h"
SPACETIMEDB_REGISTER_TYPE(RawModuleDefV9)
