// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb codegen.

#pragma once

#include <cstdint>
#include <string>
#include <vector>
#include <optional>
#include <memory>
#include "spacetimedb/bsatn/bsatn.h"

namespace SpacetimeDb::Internal {

class RawModuleDef {
public:
    enum class Tag {
        V8BackCompat = 0,
        V9 = 1,
    };

private:
    Tag tag_;
    // TODO: Implement variant storage

public:
    Tag get_tag() const { return tag_; }

    // BSATN serialization support
    void bsatn_serialize(SpacetimeDb::bsatn::Writer& writer) const;
    void bsatn_deserialize(SpacetimeDb::bsatn::Reader& reader);
};
} // namespace SpacetimeDb::Internal
#include "spacetimedb/macros.h"
SPACETIMEDB_REGISTER_TYPE(RawModuleDef)
