// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb codegen.

#pragma once

#include <cstdint>
#include <string>
#include <vector>
#include <optional>
#include <memory>
#include "spacetimedb/bsatn/bsatn.h"
#include "MiscModuleExport.g.h"
#include "ReducerDef.g.h"
#include "TableDesc.g.h"
#include "Typespace.g.h"

namespace SpacetimeDb::Internal {

struct RawModuleDefV8 {
    Typespace typespace;
    std::vector<TableDesc> tables;
    std::vector<ReducerDef> reducers;
    std::vector<MiscModuleExport> misc_exports;

    RawModuleDefV8() = default;

    RawModuleDefV8(Typespace typespace, std::vector<TableDesc> tables, std::vector<ReducerDef> reducers, std::vector<MiscModuleExport> misc_exports)
        : typespace(typespace), tables(tables), reducers(reducers), misc_exports(misc_exports) {}

    // BSATN serialization support
    void bsatn_serialize(SpacetimeDb::bsatn::Writer& writer) const;
    void bsatn_deserialize(SpacetimeDb::bsatn::Reader& reader);

    // Static factory method for BSATN deserialization
    static RawModuleDefV8 from_bsatn(SpacetimeDb::bsatn::Reader& reader) {
        RawModuleDefV8 result;
        result.bsatn_deserialize(reader);
        return result;
    }
};
} // namespace SpacetimeDb::Internal
