// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb codegen.

#pragma once

#include <cstdint>
#include <string>
#include <vector>
#include <optional>
#include <memory>
#include "spacetimedb/bsatn/bsatn.h"
#include "Lifecycle.g.h"
#include "ProductType.g.h"

namespace SpacetimeDb::Internal {

struct RawReducerDefV9 {
    std::string name;
    ProductType params;
    std::optional<Lifecycle> lifecycle;

    RawReducerDefV9() = default;

    RawReducerDefV9(std::string name, ProductType params, std::optional<Lifecycle> lifecycle)
        : name(name), params(params), lifecycle(lifecycle) {}

    // BSATN serialization support
    void bsatn_serialize(SpacetimeDb::bsatn::Writer& writer) const;
    void bsatn_deserialize(SpacetimeDb::bsatn::Reader& reader);

    // Static factory method for BSATN deserialization
    static RawReducerDefV9 from_bsatn(SpacetimeDb::bsatn::Reader& reader) {
        RawReducerDefV9 result;
        result.bsatn_deserialize(reader);
        return result;
    }
};
} // namespace SpacetimeDb::Internal
