// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb codegen.

#pragma once

#include <cstdint>
#include <string>
#include <vector>
#include <optional>
#include <memory>
#include "spacetimedb/bsatn/bsatn.h"
#include "ProductType.g.h"
#include "Lifecycle.g.h"

namespace SpacetimeDb::Internal {

struct RawReducerDefV9 {
    std::string name;
    SpacetimeDb::Internal::ProductType params;
    std::optional<SpacetimeDb::Internal::Lifecycle> lifecycle;

    RawReducerDefV9() = default;

    RawReducerDefV9(std::string name, SpacetimeDb::Internal::ProductType params, std::optional<SpacetimeDb::Internal::Lifecycle> lifecycle)
        : name(name), params(params), lifecycle(lifecycle) {}

    // BSATN serialization support
    void bsatn_serialize(SpacetimeDb::bsatn::Writer& writer) const;
    void bsatn_deserialize(SpacetimeDb::bsatn::Reader& reader);

    // Static factory method for BSATN deserialization
    static RawReducerDefV9 from_bsatn(SpacetimeDb::bsatn::Reader& reader) {
        RawReducerDefV9 result;
        result.bsatn_deserialize(reader);
        return result;
    }
};
} // namespace SpacetimeDb::Internal
// Type registration macro
#define SPACETIMEDB_REGISTER_TYPE_RawReducerDefV9 \
    namespace spacetimedb { \
    namespace detail { \
    template<> \
    struct TypeRegistrar<SpacetimeDb::Internal::RawReducerDefV9> { \
        static AlgebraicTypeRef register_type(TypeContext& ctx) { \
            return ctx.add(AlgebraicType::Product(std::make_unique<ProductType>(std::vector<ProductType::Element>{
    {"name", AlgebraicType::String()},
    {"params", AlgebraicType::Ref(6)},
    {"lifecycle", AlgebraicType::Option(AlgebraicType::Ref(30))}
}))); \
        } \
    }; \
    } /* namespace detail */ \
    } /* namespace spacetimedb */

