// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb codegen.

#pragma once

#include <cstdint>
#include <string>
#include <vector>
#include <optional>
#include <memory>
#include "spacetimedb/bsatn/bsatn.h"

namespace SpacetimeDb::Internal {

struct RawSequenceDefV9 {
    std::optional<std::string> name;
    uint16_t column;
    std::optional<spacetimedb::u128> start;
    std::optional<spacetimedb::u128> min_value;
    std::optional<spacetimedb::u128> max_value;
    spacetimedb::u128 increment;

    RawSequenceDefV9() = default;

    RawSequenceDefV9(std::optional<std::string> name, uint16_t column, std::optional<spacetimedb::u128> start, std::optional<spacetimedb::u128> min_value, std::optional<spacetimedb::u128> max_value, spacetimedb::u128 increment)
        : name(name), column(column), start(start), min_value(min_value), max_value(max_value), increment(increment) {}

    // BSATN serialization support
    void bsatn_serialize(SpacetimeDb::bsatn::Writer& writer) const;
    void bsatn_deserialize(SpacetimeDb::bsatn::Reader& reader);

    // Static factory method for BSATN deserialization
    static RawSequenceDefV9 from_bsatn(SpacetimeDb::bsatn::Reader& reader) {
        RawSequenceDefV9 result;
        result.bsatn_deserialize(reader);
        return result;
    }
};
} // namespace SpacetimeDb::Internal
// Type registration macro
#define SPACETIMEDB_REGISTER_TYPE_RawSequenceDefV9 \
    namespace spacetimedb { \
    namespace detail { \
    template<> \
    struct TypeRegistrar<SpacetimeDb::Internal::RawSequenceDefV9> { \
        static AlgebraicTypeRef register_type(TypeContext& ctx) { \
            return ctx.add(AlgebraicType::Product(std::make_unique<ProductType>(std::vector<ProductType::Element>{
    {"name", AlgebraicType::Option(AlgebraicType::String())},
    {"column", AlgebraicType::U16()},
    {"start", AlgebraicType::Option(AlgebraicType::I128())},
    {"min_value", AlgebraicType::Option(AlgebraicType::I128())},
    {"max_value", AlgebraicType::Option(AlgebraicType::I128())},
    {"increment", AlgebraicType::I128()}
}))); \
        } \
    }; \
    } /* namespace detail */ \
    } /* namespace spacetimedb */

