// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb codegen.

#pragma once

#include <cstdint>
#include <string>
#include <vector>
#include <optional>
#include <memory>
#include "spacetimedb/bsatn/bsatn.h"

namespace SpacetimeDb::Internal {

struct RawSequenceDefV9 {
    std::optional<std::string> name;
    uint16_t column;
    std::optional<SpacetimeDb::Types::int128_t_placeholder> start;
    std::optional<SpacetimeDb::Types::int128_t_placeholder> min_value;
    std::optional<SpacetimeDb::Types::int128_t_placeholder> max_value;
    SpacetimeDb::Types::int128_t_placeholder increment;

    RawSequenceDefV9() = default;

    RawSequenceDefV9(std::optional<std::string> name, uint16_t column, std::optional<SpacetimeDb::Types::int128_t_placeholder> start, std::optional<SpacetimeDb::Types::int128_t_placeholder> min_value, std::optional<SpacetimeDb::Types::int128_t_placeholder> max_value, SpacetimeDb::Types::int128_t_placeholder increment)
        : name(name), column(column), start(start), min_value(min_value), max_value(max_value), increment(increment) {}

    // BSATN serialization support
    void bsatn_serialize(SpacetimeDb::bsatn::Writer& writer) const;
    void bsatn_deserialize(SpacetimeDb::bsatn::Reader& reader);

    // Static factory method for BSATN deserialization
    static RawSequenceDefV9 from_bsatn(SpacetimeDb::bsatn::Reader& reader) {
        RawSequenceDefV9 result;
        result.bsatn_deserialize(reader);
        return result;
    }
};
} // namespace SpacetimeDb::Internal
