// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb codegen.

#pragma once

#include <cstdint>
#include <string>
#include <vector>
#include <optional>
#include <memory>
#include "spacetimedb/bsatn/bsatn.h"

namespace SpacetimeDb::Internal {

struct RawScheduleDefV9 {
    std::optional<std::string> name;
    std::string reducer_name;
    uint16_t scheduled_at_column;

    RawScheduleDefV9() = default;

    RawScheduleDefV9(std::optional<std::string> name, std::string reducer_name, uint16_t scheduled_at_column)
        : name(name), reducer_name(reducer_name), scheduled_at_column(scheduled_at_column) {}

    // BSATN serialization support
    void bsatn_serialize(SpacetimeDb::bsatn::Writer& writer) const;
    void bsatn_deserialize(SpacetimeDb::bsatn::Reader& reader);

    // Static factory method for BSATN deserialization
    static RawScheduleDefV9 from_bsatn(SpacetimeDb::bsatn::Reader& reader) {
        RawScheduleDefV9 result;
        result.bsatn_deserialize(reader);
        return result;
    }
};
} // namespace SpacetimeDb::Internal
#include "spacetimedb/macros.h"
SPACETIMEDB_REGISTER_TYPE(RawScheduleDefV9)
