// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb codegen.

#pragma once

#include <cstdint>
#include <string>
#include <vector>
#include <optional>
#include <memory>
#include "spacetimedb/bsatn/bsatn.h"

namespace SpacetimeDb::Internal {

struct RawScheduleDefV9 {
    std::optional<std::string> name;
    std::string reducer_name;
    uint16_t scheduled_at_column;

    RawScheduleDefV9() = default;

    RawScheduleDefV9(std::optional<std::string> name, std::string reducer_name, uint16_t scheduled_at_column)
        : name(name), reducer_name(reducer_name), scheduled_at_column(scheduled_at_column) {}

    // BSATN serialization support
    void bsatn_serialize(SpacetimeDb::bsatn::Writer& writer) const;
    void bsatn_deserialize(SpacetimeDb::bsatn::Reader& reader);

    // Static factory method for BSATN deserialization
    static RawScheduleDefV9 from_bsatn(SpacetimeDb::bsatn::Reader& reader) {
        RawScheduleDefV9 result;
        result.bsatn_deserialize(reader);
        return result;
    }
};
} // namespace SpacetimeDb::Internal
// Type registration macro
#define SPACETIMEDB_REGISTER_TYPE_RawScheduleDefV9 \
    namespace spacetimedb { \
    namespace detail { \
    template<> \
    struct TypeRegistrar<SpacetimeDb::Internal::RawScheduleDefV9> { \
        static AlgebraicTypeRef register_type(TypeContext& ctx) { \
            return ctx.add(AlgebraicType::Product(std::make_unique<ProductType>(std::vector<ProductType::Element>{
    {"name", AlgebraicType::Option(AlgebraicType::String())},
    {"reducer_name", AlgebraicType::String()},
    {"scheduled_at_column", AlgebraicType::U16()}
}))); \
        } \
    }; \
    } /* namespace detail */ \
    } /* namespace spacetimedb */

