// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb codegen.

#pragma once

#include <cstdint>
#include <string>
#include <vector>
#include <optional>
#include <memory>
#include "spacetimedb/bsatn/bsatn.h"

namespace SpacetimeDb::Internal {

struct RawScopedTypeNameV9 {
    std::vector<std::string> scope;
    std::string name;

    RawScopedTypeNameV9() = default;

    RawScopedTypeNameV9(std::vector<std::string> scope, std::string name)
        : scope(scope), name(name) {}

    // BSATN serialization support
    void bsatn_serialize(SpacetimeDb::bsatn::Writer& writer) const;
    void bsatn_deserialize(SpacetimeDb::bsatn::Reader& reader);

    // Static factory method for BSATN deserialization
    static RawScopedTypeNameV9 from_bsatn(SpacetimeDb::bsatn::Reader& reader) {
        RawScopedTypeNameV9 result;
        result.bsatn_deserialize(reader);
        return result;
    }
};
} // namespace SpacetimeDb::Internal
// Type registration macro
#define SPACETIMEDB_REGISTER_TYPE_RawScopedTypeNameV9 \
    namespace spacetimedb { \
    namespace detail { \
    template<> \
    struct TypeRegistrar<SpacetimeDb::Internal::RawScopedTypeNameV9> { \
        static AlgebraicTypeRef register_type(TypeContext& ctx) { \
            return ctx.add(AlgebraicType::Product(std::make_unique<ProductType>(std::vector<ProductType::Element>{
    {"scope", AlgebraicType::Array(std::make_unique<ArrayType>(AlgebraicType::String())))},
    {"name", AlgebraicType::String()}
}))); \
        } \
    }; \
    } /* namespace detail */ \
    } /* namespace spacetimedb */

