// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb codegen.

#pragma once

#include <cstdint>
#include <string>
#include <vector>
#include <optional>
#include <memory>
#include "spacetimedb/bsatn/bsatn.h"
#include "RawScopedTypeNameV9.g.h"

namespace SpacetimeDb::Internal {

struct RawTypeDefV9 {
    RawScopedTypeNameV9 name;
    uint32_t ty;
    bool custom_ordering;

    RawTypeDefV9() = default;

    RawTypeDefV9(RawScopedTypeNameV9 name, uint32_t ty, bool custom_ordering)
        : name(name), ty(ty), custom_ordering(custom_ordering) {}

    // BSATN serialization support
    void bsatn_serialize(SpacetimeDb::bsatn::Writer& writer) const;
    void bsatn_deserialize(SpacetimeDb::bsatn::Reader& reader);

    // Static factory method for BSATN deserialization
    static RawTypeDefV9 from_bsatn(SpacetimeDb::bsatn::Reader& reader) {
        RawTypeDefV9 result;
        result.bsatn_deserialize(reader);
        return result;
    }
};
} // namespace SpacetimeDb::Internal
