// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb codegen.

#pragma once

#include <cstdint>
#include <string>
#include <vector>
#include <optional>
#include <memory>
#include "spacetimedb/bsatn/bsatn.h"
#include "RawConstraintDefV9.g.h"
#include "RawIndexDefV9.g.h"
#include "RawScheduleDefV9.g.h"
#include "RawSequenceDefV9.g.h"
#include "TableAccess.g.h"
#include "TableType.g.h"

namespace SpacetimeDb::Internal {

struct RawTableDefV9 {
    std::string name;
    uint32_t product_type_ref;
    std::vector<uint16_t> primary_key;
    std::vector<RawIndexDefV9> indexes;
    std::vector<RawConstraintDefV9> constraints;
    std::vector<RawSequenceDefV9> sequences;
    std::optional<RawScheduleDefV9> schedule;
    TableType table_type;
    TableAccess table_access;

    RawTableDefV9() = default;

    RawTableDefV9(std::string name, uint32_t product_type_ref, std::vector<uint16_t> primary_key, std::vector<RawIndexDefV9> indexes, std::vector<RawConstraintDefV9> constraints, std::vector<RawSequenceDefV9> sequences, std::optional<RawScheduleDefV9> schedule, TableType table_type, TableAccess table_access)
        : name(name), product_type_ref(product_type_ref), primary_key(primary_key), indexes(indexes), constraints(constraints), sequences(sequences), schedule(schedule), table_type(table_type), table_access(table_access) {}

    // BSATN serialization support
    void bsatn_serialize(SpacetimeDb::bsatn::Writer& writer) const;
    void bsatn_deserialize(SpacetimeDb::bsatn::Reader& reader);

    // Static factory method for BSATN deserialization
    static RawTableDefV9 from_bsatn(SpacetimeDb::bsatn::Reader& reader) {
        RawTableDefV9 result;
        result.bsatn_deserialize(reader);
        return result;
    }
};
} // namespace SpacetimeDb::Internal
