// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb codegen.

#pragma once

#include <cstdint>
#include <string>
#include <vector>
#include <optional>
#include <memory>
#include "spacetimedb/bsatn/bsatn.h"
#include "RawColumnDefV8.g.h"
#include "RawConstraintDefV8.g.h"
#include "RawIndexDefV8.g.h"
#include "RawSequenceDefV8.g.h"

namespace SpacetimeDb::Internal {

struct RawTableDefV8 {
    std::string table_name;
    std::vector<RawColumnDefV8> columns;
    std::vector<RawIndexDefV8> indexes;
    std::vector<RawConstraintDefV8> constraints;
    std::vector<RawSequenceDefV8> sequences;
    std::string table_type;
    std::string table_access;
    std::optional<std::string> scheduled;

    RawTableDefV8() = default;

    RawTableDefV8(std::string table_name, std::vector<RawColumnDefV8> columns, std::vector<RawIndexDefV8> indexes, std::vector<RawConstraintDefV8> constraints, std::vector<RawSequenceDefV8> sequences, std::string table_type, std::string table_access, std::optional<std::string> scheduled)
        : table_name(table_name), columns(columns), indexes(indexes), constraints(constraints), sequences(sequences), table_type(table_type), table_access(table_access), scheduled(scheduled) {}

    // BSATN serialization support
    void bsatn_serialize(SpacetimeDb::bsatn::Writer& writer) const;
    void bsatn_deserialize(SpacetimeDb::bsatn::Reader& reader);

    // Static factory method for BSATN deserialization
    static RawTableDefV8 from_bsatn(SpacetimeDb::bsatn::Reader& reader) {
        RawTableDefV8 result;
        result.bsatn_deserialize(reader);
        return result;
    }
};
} // namespace SpacetimeDb::Internal
