// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb codegen.

#pragma once

#include <cstdint>
#include <string>
#include <vector>
#include <optional>
#include <memory>
#include "spacetimedb/bsatn/bsatn.h"
#include "AlgebraicType.g.h"

namespace SpacetimeDb::Internal {

struct SumTypeVariant {
    std::optional<std::string> name;
    SpacetimeDb::Internal::AlgebraicType algebraic_type;

    SumTypeVariant() = default;

    SumTypeVariant(std::optional<std::string> name, SpacetimeDb::Internal::AlgebraicType algebraic_type)
        : name(name), algebraic_type(algebraic_type) {}

    // BSATN serialization support
    void bsatn_serialize(SpacetimeDb::bsatn::Writer& writer) const;
    void bsatn_deserialize(SpacetimeDb::bsatn::Reader& reader);

    // Static factory method for BSATN deserialization
    static SumTypeVariant from_bsatn(SpacetimeDb::bsatn::Reader& reader) {
        SumTypeVariant result;
        result.bsatn_deserialize(reader);
        return result;
    }
};
} // namespace SpacetimeDb::Internal
#include "spacetimedb/macros.h"
SPACETIMEDB_REGISTER_TYPE(SumTypeVariant)
