// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb codegen.

#pragma once

#include <cstdint>
#include <string>
#include <vector>
#include <optional>
#include <memory>
#include "spacetimedb/bsatn/bsatn.h"
#include "RawTableDefV8.g.h"

namespace SpacetimeDb::Internal {

struct TableDesc {
    SpacetimeDb::Internal::RawTableDefV8 schema;
    uint32_t data;

    TableDesc() = default;

    TableDesc(SpacetimeDb::Internal::RawTableDefV8 schema, uint32_t data)
        : schema(schema), data(data) {}

    // BSATN serialization support
    void bsatn_serialize(SpacetimeDb::bsatn::Writer& writer) const;
    void bsatn_deserialize(SpacetimeDb::bsatn::Reader& reader);

    // Static factory method for BSATN deserialization
    static TableDesc from_bsatn(SpacetimeDb::bsatn::Reader& reader) {
        TableDesc result;
        result.bsatn_deserialize(reader);
        return result;
    }
};
} // namespace SpacetimeDb::Internal
// Type registration macro
#define SPACETIMEDB_REGISTER_TYPE_TableDesc \
    namespace spacetimedb { \
    namespace detail { \
    template<> \
    struct TypeRegistrar<SpacetimeDb::Internal::TableDesc> { \
        static AlgebraicTypeRef register_type(TypeContext& ctx) { \
            return ctx.add(AlgebraicType::Product(std::make_unique<ProductType>(std::vector<ProductType::Element>{
    {"schema", AlgebraicType::Ref(9)},
    {"data", AlgebraicType::U32()}
}))); \
        } \
    }; \
    } /* namespace detail */ \
    } /* namespace spacetimedb */

