// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb codegen.

#pragma once

#include <cstdint>
#include <string>
#include <vector>
#include <optional>
#include <memory>
#include "spacetimedb/bsatn/bsatn.h"

namespace SpacetimeDb::Internal {

enum class TableType {
    System = 0,
    User = 1,
};
} // namespace SpacetimeDb::Internal

// BSATN serialization for TableType
namespace SpacetimeDb::bsatn {
    inline void serialize(Writer& w, const SpacetimeDb::Internal::TableType& value) {
        w.write_u8(static_cast<uint8_t>(value));
    }

    template<>
    inline SpacetimeDb::Internal::TableType deserialize<SpacetimeDb::Internal::TableType>(Reader& r) {
        return static_cast<SpacetimeDb::Internal::TableType>(r.read_u8());
    }
}
