// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb codegen.

#pragma once

#include <cstdint>
#include <string>
#include <vector>
#include <optional>
#include <memory>
#include "spacetimedb/bsatn/bsatn.h"
#include "RawTableDefV8.g.h"

namespace SpacetimeDb::Internal {

struct TableDesc {
    SPACETIMEDB_DATA_MEMBER("schema")
    SpacetimeDb::Internal::RawTableDefV8 schema;
    SPACETIMEDB_DATA_MEMBER("data")
    uint32_t data;

    TableDesc() = default;

    TableDesc(SpacetimeDb::Internal::RawTableDefV8 schema, uint32_t data)
        : schema(schema), data(data) {}

    // BSATN serialization support
    void bsatn_serialize(SpacetimeDb::bsatn::Writer& writer) const;
    void bsatn_deserialize(SpacetimeDb::bsatn::Reader& reader);

    // Static factory method for BSATN deserialization
    static TableDesc from_bsatn(SpacetimeDb::bsatn::Reader& reader) {
        TableDesc result;
        result.bsatn_deserialize(reader);
        return result;
    }
};
} // namespace SpacetimeDb::Internal
#include "spacetimedb/macros.h"
SPACETIMEDB_TYPE(TableDesc)
SPACETIMEDB_DATA_CONTRACT
SPACETIMEDB_REGISTER_TYPE(TableDesc)
