#!/bin/bash

# Script to fix namespace inconsistencies in C++ Module Library
# Changes all occurrences of "namespace spacetimedb" to "namespace SpacetimeDb"

echo "Fixing namespace inconsistencies in C++ Module Library..."

# Find all C++ files
find . -type f \( -name "*.h" -o -name "*.cpp" \) -print0 | while IFS= read -r -d '' file; do
    # Skip autogenerated files
    if [[ "$file" == *".g.h"* ]] || [[ "$file" == *".g.cpp"* ]]; then
        continue
    fi
    
    # Create a temporary file
    temp_file="${file}.tmp"
    
    # Perform replacements
    sed -e 's/namespace spacetimedb/namespace SpacetimeDb/g' \
        -e 's/spacetimedb::/SpacetimeDb::/g' \
        -e 's/using namespace spacetimedb/using namespace SpacetimeDb/g' \
        -e 's/spacetimedb::bsatn/SpacetimeDb::bsatn/g' \
        -e 's/} \/\/ namespace spacetimedb/} \/\/ namespace SpacetimeDb/g' \
        -e 's/} \/\/namespace spacetimedb/} \/\/namespace SpacetimeDb/g' \
        "$file" > "$temp_file"
    
    # Check if file was modified
    if ! cmp -s "$file" "$temp_file"; then
        mv "$temp_file" "$file"
        echo "Fixed: $file"
    else
        rm "$temp_file"
    fi
done

echo "Namespace fixes complete!"